### PR TITLE
add map for LIS spot room 45-621

### PR DESCRIPTION
**Pull request by lf-zhao**
major actions:
- map the MIT LIS Spot room, 45-621
- add metadata of the room
- add notes in readme on the steps to add new environment/task for Spot

### CODE REVIEW

**Comment by NishanthJKumar** [comment]
Thanks for doing this @lf-zhao ; could you add [metadata file](https://github.com/bdaiinstitute/predicators/tree/master/predicators/spot_utils#mapping)

**Comment by lf-zhao** [comment]
Let me look into it!

Separate issue: any idea what causing this even when I never touched that file?
```
Run mypy . --config-file mypy.ini
predicators/spot_utils/perception/object_detection.py:2[7](https://github.com/bdaiinstitute/predicators/actions/runs/8525754028/job/23353458231?pr=280#step:5:8)7: error: Call to untyped function "fromarray" in typed context
Found 1 error in 1 file (checked 399 source files)
```

**Comment by retriever-share** [comment]
I think the map + metadata is done! I might need help on the static type checking, other than that should be good

**Comment by NishanthJKumar** [comment]
Awesome - I can look into the mypy issue. 
If possible, could you update the main description of the pr with some text describing everything you've added here? Will help us keep track of which pr adds what info

**Comment by lf-zhao** [comment]
Thanks! Yep, done with that!

**Comment by NishanthJKumar** [comment]
superseded by #281

**Pull request closed without merging**
